version: "3"

services:
  appserver:
    build: .
    container_name: "appserver-fastapi"
    restart: always
    environment:
      - name=value
    ports:
      - "8000:8000"
    volumes:
      - ./appserver/:/appserver

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - ":"
    volumes:
      - ":"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
