version: "3"

services:
  appserver:
    build: .
    container_name: "appserver-fastapi"
    restart: always
    environment:
      - name=value
    ports:
      - "8000:8000"
    volumes:
      - ./appserver/:.
    links:
      - redis

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - ":"
    volumes:
      - "redis-cache-db:/var/lib/redis/data"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - appserver
    ports:
      - "80:80"


volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local


# postgres:var/lib/postgress/data
# /var/lib/docker/volumes
