- name: install nginx on all servers
  hosts: webservers
  remote_user: ansible
  become: true
  
  tasks:
    - name: install nginx 
      apt:
        name: nginx
        state: latest

    - name: apply nginx template
      template:
        src: .../nginx.conf
        dest: /etc/nginx/sites-available/default
        notify: restart nginx

    - name: copy files try
      copy:
        src: "variable"
        dest: /path
        mode: preserve

    - name: start nginx
      service:
        name: nginx
        start: started
  
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted