- name: install nginx on all servers
  hosts: "webservers"
  remote_user: root
  become: true
  
  tasks:
    - name: create nginx location
      apt:
        path:
        state:

    - name: install nginx 
      yum:
        name: nginx
        state: latest
    
    - name: start nginx
      service:
        name: nginx
        start: started